export interface Paciente {
    primerNombre: string,
    segundoNombre?: string,
    primerApellido: string,
    segundoApellido?: string,
    tipoDocumento: string,
    numeroDocumento: string,
    genero: string,
    estadoCivil: string,
    fechaNacimiento: Date,
    ciudadNacimiento: string,
    departamentoNacimiento: string,
    paisNacimiento: string,
    direccionResidencia: string,
    ciudadResidencia: string,
    departamentoResidencia: string,
    paisResidencia: string,
    telefono?: string,
    correoElectronico?: string,
    nivelEscolaridad?: string,
    profesionOficio?: string,
    arl?: string,
    eps?: string,
    afp?: string,
    estado: boolean
}
